### ISSUE TITLE
Socket.io v3 support for this package?

### ISSUE THREAD

**Issue by gtwilliams03** [auth0-community/auth0-socketio-jwt#178]
### Description

Error using this package with recently-released socket.io v3.

### Expected behaviour

No errors during authentication.

### Actual behaviour 

Error running previously-working package after installing and configuring for socket.io v3.

Error thrown during socket.io-jwt `authenticate` call:

```
/node_modules/socketio-jwt/lib/index.js:16
      if (!~Namespace.events.indexOf('authenticated')) {
                             ^

TypeError: Cannot read property 'indexOf' of undefined
    at Namespace.<anonymous> (/node_modules/socketio-jwt/lib/index.js:16:30)
    at Namespace.emit (events.js:326:22)
    at /node_modules/socket.io/dist/namespace.js:129:27
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

The error is thrown in the socket.io-jwt package here (for starters) - have not gotten past this yet.

```
    if (!server.$emit) {
      //then is socket.io 1.0
      const Namespace = Object.getPrototypeOf(server.sockets).constructor;
      if (!~Namespace.events.indexOf('authenticated')) {
        Namespace.events.push('authenticated');
      }
    }

```

### Steps to reproduce the problem

Run socket.io-jwt with socket.io v3.

### Language / Framework Versions

1. Javascript
2. Node 14.13.1

### Testing environment

1. MacOS
2. None.

**Comment by gtwilliams03** [comment]
Migration guide for v2 -> v3 for socket.io is [here](https://socket.io/docs/migrating-from-2-x-to-3-0/#Configuration) and I the issue may be that the Namespace.events property is no longer there or is a different structure.  The migration guide indicates that rooms are now typescript Sets, etc.

**Comment by Divlo** [comment]
Same problem.

Since this commit : https://github.com/socketio/socket.io/commit/5c737339858d59eab4b5ee2dd6feff0e82c4fe5a
The `socket.use()` method is removed but to use `socketio-jwt`, we need to that kind of code with socket.io >= 1.0 (as it is said in the README in the Usage part) : 
```js
io.use(socketioJwt.authorize({
  secret: 'your secret or public key',
  handshake: true
}));
```
Instead it is replaced with this :
```js
socket.onAny((event, ...args) => {  
  console.log(event)
})
```
It takes different argument, that's certainly why the authorize method break, we need to change it to work with socket.io >= 3.

**Comment by Divlo** [comment]
Could you take a look, please ? @konradsopala

**Comment by konradsopala** [comment]
Hey there!

Unfortunately I'm no longer responsible for maintaining that repo.

**Comment by Divlo** [comment]
Alright @konradsopala, who is responsible to maintain the repo ? If there is no one, I could fork the repo and try to maintain it, what do you think ?

**Comment by konradsopala** [comment]
We're at the stage of establishing a maintenance framework just for this case so that people who are willing to take it will be able to maintain that co-operating from time to time with Auth0 engineers. Will let you guys know once it's there!

**Comment by gtwilliams03** [comment]
Thank you @Divlo and @konradsopala!  I am going to roll back socket.io in my project for now and will watch this repo for updates!

**Comment by Phygon** [comment]
> Since this commit : [socketio/socket.io@5c73733](https://github.com/socketio/socket.io/commit/5c737339858d59eab4b5ee2dd6feff0e82c4fe5a)
> The `socket.use()` method is removed but to use `socketio-jwt`, we need to have that kind of code with socket.io >= 1.0 (as it is said in the README in the Usage part) :

No. The `io.use()` or `io.sockets.use()` for middleware is still there. Only `socket.use()` was removed.

The problem is, that internal data structures have changed.

Also sio 2.x cannot connect to sio 3.x servers and vice versa, so it is probably better to stay with sio 2.x and plan for an upgrade path.

**Comment by dverzolla** [comment]
Watching for a solution.

**Comment by Divlo** [comment]
Good news! @dverzolla @gtwilliams03 
I decided to duplicate the repository, available there : [Thream/socketio-jwt](https://www.npmjs.com/package/@thream/socketio-jwt). It is compatible with `socket.io >= 3.0`.

**Note:** Some features are missing from this package. 
I'd rather to have one way to do something than many ways. This package had many ways to authenticate with the token, for example with the query or with authorization header etc.
So I deleted all the "unnecessary" code and only leave one way to use the package.
Now the `README` is way smaller and It is easier for new users to use this package.

Also I rewrite completely the code in TypeScript and write the tests in `jest` instead of `mocha` because we were using a old version of `mocha` and had vulnerabilities, new version of `mocha` broke the tests.
If you dive into the code, you'll see there is not so much same way as before, that's because it was an old code base, difficult to maintain and update so rewrite it would be much easier.

I already used the package in one of my project and everything is working fine and we've got 100% tests coverage but if you find bugs or need some feature that are necessary and I accidentally deleted, feel free to open issues and PRs.

Could you deprecate your package on npm and link to the new package ? @konradsopala 
Thanks!

**Comment by dverzolla** [comment]
Hey @Divlo, congrats for your contribution. I was eagerly waiting for updates. Let's wait @konradsopala decision.

**Comment by dobby5** [comment]
Hello @Divlo ,

first of all thank you for your efforts.
I have added your version to my project and I notice that the RS256 support is missing or no longer behaves in the traditional way. 

It might be of interest to you that I use jwks-rsa in combination.

An implementation would be very helpful :)

**Comment by Divlo** [comment]
Sure, thanks for your feedback! Could you open an issue on the repo, please ? @dobby5 
Could you also tell me how did you used this package (what options do you pass to `authorize` with the old package) to support RS256 ?

**Comment by dobby5** [comment]
I must say that I use the solution of ssnxd (folk).

However, that does not change that this feature would be very helpful. I have created an issue.

Thank you for that.

**Comment by Divlo** [comment]
**Update :** `@thream/socketio-jwt@1.1.0` now support `jwks-rsa`, if you have others feature request or bugs, feel free to open issues in the repo.

@dverzolla While we're waiting for @konradsopala answer, you could already `npm install @thream/socketio-jwt` and tell us if everything is working as expected and give feedbacks. :smile:

**Comment by dverzolla** [comment]
@Divlo I'm tied in some projects. Will try to test this week.

**Comment by konradsopala** [comment]
Hey there everyone! The maintenance framework for auth0-community org repos is constantly being worked on and we're getting closer and closer to the end but no public facing decision has been made just yet regarding that. As you can see browsing through other auth0-community repos some of them have been deprecated and archived in the meantime. Does anyone from this thread will be potentially interested in co-maintaining that repo with some Auth0 engineers?

**Comment by Divlo** [comment]
Hey @konradsopala! 👋
Maybe we can do the same things as you did for others *auth0-community repos* for this repo.
As you can see on my last messages, I completely rewrote this package in another repo, and I feel like it's weird to maintain the same package in 2 seperated repos, so what do you think is the best solution ?

- We could archive and deprecate this package and link to the new package `@thream/socketio-jwt`.
- We could get all the improved code (updated dependencies, TypeScript support etc.) from `Thream` repo and move opy all the repo files in this repo again, so we could delete `Thream` repo.

It's up to you, but what we want as a community, is to have a maintained repo to work with `socket.io` and `jwt`, I don't want to start a "war" and it's really strange to have to maintain 2 repos for the same things, so I would rather find out a solution together to improve things **together**. :rocket:

**Comment by konradsopala** [comment]
Thanks a lot @Divlo for describing all the options you see here. I'm attaching the main stakeholders from our side so you can directly discuss that here. It would be great if you can engage here guys! @JimCMorrison @cocojoe

**Comment by JimCMorrison** [comment]
Thank you for your feedback here @Divlo and for the help @konradsopala! We will take this feedback and review it as a group on our side to fully weigh out all available options. I will keep you posted as we proceed forward, thank you.

**Comment by dverzolla** [comment]
Hey @Divlo, did the tests following the @Thream/socketio-jwt/blob/develop/README.md and everything worked properly. Congrats dude.

**Comment by getTobiasNielsen** [comment]
Didn't socket.IO  patch 3.0.5 just restore middleware functionality?
https://github.com/socketio/socket.io/issues/3678

**Comment by Divlo** [comment]
> Didn't socket.IO  patch 3.0.5 just restore middleware functionality?
> https://github.com/socketio/socket.io/issues/3678

Oh yes, you're right!
So maybe this repo work again with `socket.io >= 3.0.5`, if someone could test, and tell us how it works.

**Comment by yoruvo** [comment]
This repo does not work with socket.io 3.1.

**Comment by gersonmdesouza** [comment]
I was facing the same problem and managed to fix it using `socketio-jwt@4.6.2` and `socket.io@3.1.0 `

**Comment by Divlo** [comment]
I would still recommand to use `@thream/socketio-jwt` to have TypeScript typings builtin, less dependencies to download, and one single way to use the package so it's easier to get started with.

**Comment by dverzolla** [comment]
> 
> 
> I was facing the same problem and managed to fix it using `socketio-jwt@4.6.2` and `socket.io@3.1.0 `

Would you mind to share your code with us? Server and Client side? I'm still facing troubles.

**Comment by Divlo** [comment]
@dverzolla Could you check `@thream/socketio-jwt` package and tell us if it is working as expected ?
Link : https://www.npmjs.com/package/@thream/socketio-jwt

**Comment by getTobiasNielsen** [comment]
I solved mine with `uWebSocket.js` and auth0's `node-jsonwebtoken`. Ofc, my project didn't already depend on socket.io.

@Divlo I doubt @yoruvo had any insight, as the comment thought you used 3.1, when you originally posted, yet you stated no such thing. I'd just give it a go, any auth0 jwt middleware should do.

**Comment by dverzolla** [comment]
> 
> 
> I would still recommand to use `@thream/socketio-jwt` to have TypeScript typings builtin, less dependencies to download, and one single way to use the package so it's easier to get started with.

I did it already: https://github.com/auth0-community/auth0-socketio-jwt/issues/178#issuecomment-766450326
The usage was seamless.

**Comment by yoruvo** [comment]
> I solved mine with `uWebSocket.js` and auth0's `node-jsonwebtoken`. Ofc, my project didn't already depend on socket.io.
> 
> @Divlo I doubt @yoruvo had any insight, as the comment thought you used 3.1, when you originally posted, yet you stated no such thing. I'd just give it a go, any auth0 jwt middleware should do.

I am not sure what this means. My comment was a reference to:

> So maybe this repo work again with `socket.io >= 3.0.5`, if someone could test, and tell us how it works.

I did that (3.1.0 was the version available when I started using this package), and I was facing the same issues described in the OP, so that spoke against that assumption. Curiously, it allegedly works for @gersonmdesouza, so I dunno, really.

I switched to the Thream package and after some config, it's a working solution for me.

**Comment by gersonmdesouza** [comment]
> > I was facing the same problem and managed to fix it using `socketio-jwt@4.6.2` and `socket.io@3.1.0 `
> 
> Would you mind to share your code with us? Server and Client side? I'm still facing troubles.

@dverzolla I'm using the following code with `socketio-jwt@4.6.2` and `socket.io@3.1.0`

**Server side**

`
import express from 'express'
import http from 'http'
import { Server, Socket } from 'socket.io'

const app = express()
const server = http.createServer(app)
const io = new Server(server)

io.use(socketioJwt.authorize({
  secret: process.env.JWT_SECRET, 
  handshake: true, 
  auth_header_required: true 
}))

io.on('connection', (socket: Socket) => {
    console.log(`Socket ${socket.id} connected`)
})
`

**Client side**

`
import { io, ManagerOptions } from 'socket.io-client'

const Authorization = 'qweqweasdasdzxczxc'

const options: Partial<ManagerOptions> = {
  extraHeaders: {
    Authorization
  }
}

const socket = io(url, options)

socket.on('connect', () => {
  console.log('connected')
})
`

**Comment by getTobiasNielsen** [comment]
> I did that (3.1.0 was the version available when I started using this package), and I was facing the same issues described in the OP, so that spoke against that assumption. Curiously, it allegedly works for @gersonmdesouza, so I dunno, really.

I thought you must have had thought it was 3.1 originally and foregone a test. This is curious indeed.

**Comment by dverzolla** [comment]
> 
> 
> > > I was facing the same problem and managed to fix it using `socketio-jwt@4.6.2` and `socket.io@3.1.0 `
> > 
> > 
> > Would you mind to share your code with us? Server and Client side? I'm still facing troubles.
> 
> @dverzolla I'm using the following code with `socketio-jwt@4.6.2` and `socket.io@3.1.0`
> 
> **Server side**
> 
> ```
> import express from 'express'
> import http from 'http'
> import { Server, Socket } from 'socket.io'
> import socketioJwt from 'socketio-jwt'
> 
> const app = express()
> const server = http.createServer(app)
> const io = new Server(server)
> 
> io.use(socketioJwt.authorize({
>   secret: process.env.JWT_SECRET, 
>   handshake: true, 
>   auth_header_required: true 
> }))
> 
> io.on('connection', (socket: Socket) => {
>     console.log(`Socket ${socket.id} connected`)
> })
> ```
> 
> **Client side**
> 
> ```
> import { io, ManagerOptions } from 'socket.io-client'
> 
> const options: Partial<ManagerOptions> = {
>   extraHeaders: {
>     Authorization: 'qweqweasdasdzxczxc'
>   }
> }
> 
> const socket = io(url, options)
> 
> socket.on('connect', () => {
>   console.log('connected')
> })
> ```

Thanks.
I saw that you are using 'one roundtrip' approach. That works for me as well. However the error handling using this approach is weird, look the comments here: https://github.com/auth0-community/auth0-socketio-jwt/issues/98#issuecomment-299769096

The 'full approach' still doesn't work with socket.io 3+ versions.

**Comment by gtwilliams03** [comment]
I converted over to the @thream package and my app is working fine on socket.io v3.  You have to remove the .on('authorization') event listener because you essentially pass in an extraHeader with the bearer token so the authorization happens on connect rather than with a round trip and a second authorization emit.

**Comment by TKlie** [comment]
I am using `socket.io@3.1.0` and `socketio-jwt@4.6.2`.

My application is using the `websocket` transport exclusively, which is why I am not able to pass `extraHeaders` to the client connection - at least not when connecting from a browser (see [socket.io-client issue 1356](https://github.com/socketio/socket.io-client/issues/1356)) - and thus can't use `socketio-jwt` as a middleware (which seems to be the only way your package allows @Divlo?). Using a query string also doesn't fit my use case.

I instead tried using the in this repo's README described way of authing on `connection`. In this case the `noQsMethod` is used, which performs following check on line `13`:

```js
if (!server.$emit) {
  //then is socket.io 1.0
  const Namespace = Object.getPrototypeOf(server.sockets).constructor;
  if (!~Namespace.events.indexOf('authenticated')) {
    Namespace.events.push('authenticated');
  }
}
```

Apparently, this check causes issues because it doesn't hold for `socket.io` v3. It would now probably have to be: 

```js
if(!sever.$emit && !server.emit)
```

Additionally, on successful token verification the `authenticated` event is emitted to the namespace (line `95`) along with the `socket` object.

```js
namespace.emit('authenticated', socket);
```

This causes an encoding error, though I am not sure whether this is due to the new `socket.io` version or me using the Redis adapter:
```
Error: Could not encode
  at _encode (.../node_modules/notepack.io/lib/encode.js:256:13)
  at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
  at _encode (.../node_modules/notepack.io/lib/encode.js:246:17)
  at _encode (.../node_modules/notepack.io/lib/encode.js:246:17)
  at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
  at _encode (.../node_modules/notepack.io/lib/encode.js:246:17)
  at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
  at Object.encode (.../node_modules/notepack.io/lib/encode.js:261:41)
  at RedisAdapter.broadcast (.../node_modules/socket.io-redis/dist/index.js:259:33)
  at Namespace.emit (.../node_modules/socket.io/dist/namespace.js:181:22)
```

The former issue seems like a simple fix. I would welcome any pointers regarding the encoding issue though.

**Comment by Divlo** [comment]
The fact that I only leave one way to use this package was on purpose and I decided that the cleanest way would be to use `extraHeaders` to pass the Bearer JWT token.
(`@thream/socketio-jwt` also doesn't support query string to pass the token)

But I didn't check precisely what use case would break if I allow only to pass the token in `extraHeaders`, but I find out that it's much easier and cleaner to only use one way to use a library than many ways as it does the same thing.

I would rather solves this issue with `websocket` as transport, without adding another way to use the library with the `connection` event as it is the case with this repo, either we change the way we pass the token, and "remove" the old way or else we do nothing.

Hopefully, I'm understandable. :smile: 

Could you explain why you can't pass `extraHeaders` while using `websocket` as transpor, I don't have enough knowledge to solves this issue but it would be cool, if we could find a solution that fits everyone. @TKlie

**Comment by TKlie** [comment]
@Divlo Thanks for the explanation. I understand your reasoning as to only providing one way to pass the token.

As for the `extraHeaders` issue: This would probably work if my clients were connecting from a Node app. But I also need browser support, and it seems like most browser APIs simply do not support setting headers on `websocket` transport.

I now built my own custom authorize functionality, since I couldn't wait for the package to be fixed - and, as I mentioned, headers and query string are out of the question for me anyway, since I don't want intermediary HTTP servers to log my requests. My authorize function additionally accepts a callback to be called on successful auth - that way I can avoid the encoding issue.

**Comment by skipper09** [comment]
> I am using `socket.io@3.1.0` and `socketio-jwt@4.6.2`.
> 
> My application is using the `websocket` transport exclusively, which is why I am not able to pass `extraHeaders` to the client connection - at least not when connecting from a browser (see [socket.io-client issue 1356](https://github.com/socketio/socket.io-client/issues/1356)) - and thus can't use `socketio-jwt` as a middleware (which seems to be the only way your package allows @Divlo?). Using a query string also doesn't fit my use case.
> 
> I instead tried using the in this repo's README described way of authing on `connection`. In this case the `noQsMethod` is used, which performs following check on line `13`:
> 
> ```js
> if (!server.$emit) {
>   //then is socket.io 1.0
>   const Namespace = Object.getPrototypeOf(server.sockets).constructor;
>   if (!~Namespace.events.indexOf('authenticated')) {
>     Namespace.events.push('authenticated');
>   }
> }
> ```
> 
> Apparently, this check causes issues because it doesn't hold for `socket.io` v3. It would now probably have to be:
> 
> ```js
> if(!sever.$emit && !server.emit)
> ```
> 
> Additionally, on successful token verification the `authenticated` event is emitted to the namespace (line `95`) along with the `socket` object.
> 
> ```js
> namespace.emit('authenticated', socket);
> ```
> 
> This causes an encoding error, though I am not sure whether this is due to the new `socket.io` version or me using the Redis adapter:
> 
> ```
> Error: Could not encode
>   at _encode (.../node_modules/notepack.io/lib/encode.js:256:13)
>   at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
>   at _encode (.../node_modules/notepack.io/lib/encode.js:246:17)
>   at _encode (.../node_modules/notepack.io/lib/encode.js:246:17)
>   at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
>   at _encode (.../node_modules/notepack.io/lib/encode.js:246:17)
>   at _encode (.../node_modules/notepack.io/lib/encode.js:162:19)
>   at Object.encode (.../node_modules/notepack.io/lib/encode.js:261:41)
>   at RedisAdapter.broadcast (.../node_modules/socket.io-redis/dist/index.js:259:33)
>   at Namespace.emit (.../node_modules/socket.io/dist/namespace.js:181:22)
> ```
> 
> The former issue seems like a simple fix. I would welcome any pointers regarding the encoding issue though.

Hey did you get this fixed? I'm running into this issue too. Also using socket.io-redis. Thanks.

**Comment by dverzolla** [comment]
@skipper09 did you try the native token provided by socket.io? 

https://socket.io/docs/v3/client-initialization/#auth

you could use `socket.handshake.auth` and pass the jwt token thru it.

**Comment by TKlie** [comment]
@skipper09 Please excuse the late reply. No I did not get this fixed. Like I said in my last post, I ended up writing my own authentication functionality, tailored to my application's needs. It doesn't really do too much differently - except that it works with (and only) `socket.io@^3.0` since that's the only thing I need to be compatible with.

**Comment by SayakMukhopadhyay** [comment]
We will be using an authenticated websocket in production so we will need to use this library for the visible future. As such I am also interested in maintaining this library. For now, I am using @Divlo 's fork and it seems to work great with Socket.io@3.

I would also prefer to have a single project for this library.

**Comment by adamreisnz** [comment]
@Divlo does your version by any chance address the issue of lacking support for dynamic namespaces?

See https://github.com/auth0-community/auth0-socketio-jwt/issues/174

**Comment by Divlo** [comment]
> @Divlo does your version by any chance address the issue of lacking support for dynamic namespaces?
> 
> See https://github.com/auth0-community/auth0-socketio-jwt/issues/174

We're not using the `authenticate` event, so I guess, it's not working.

**Comment by ram-you** [comment]
And FYI, Socket.io v4 is is already published.

**Comment by Divlo** [comment]
Yep, and good news, `@thream/socketio-jwt` is compatible with `socket.io@4.0.0`.

**Comment by Divlo** [comment]
See discussion about the future of this package there: https://community.auth0.com/t/community-repo-deprecations-september-2021-eol/60380
